export const RecoveryManagerAbi = [
  {
    type: 'constructor',
    inputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelRecovery',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'challengePeriod',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'executeRecovery',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getGuardian',
    inputs: [{ name: 'index', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct GuardianLib.Guardian',
        components: [
          {
            name: 'guardianType',
            type: 'uint8',
            internalType: 'enum GuardianLib.GuardianType',
          },
          { name: 'identifier', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSession',
    inputs: [],
    outputs: [
      { name: 'intentHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'newOwner', type: 'address', internalType: 'address' },
      { name: 'deadline', type: 'uint256', internalType: 'uint256' },
      { name: 'thresholdMetAt', type: 'uint256', internalType: 'uint256' },
      { name: 'approvalCount', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'guardianCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasApproved',
    inputs: [
      {
        name: 'guardianIdentifier',
        type: 'bytes32',
        internalType: 'bytes32',
      },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: '_wallet', type: 'address', internalType: 'address' },
      {
        name: 'guardians',
        type: 'tuple[]',
        internalType: 'struct GuardianLib.Guardian[]',
        components: [
          {
            name: 'guardianType',
            type: 'uint8',
            internalType: 'enum GuardianLib.GuardianType',
          },
          { name: 'identifier', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
      { name: '_threshold', type: 'uint256', internalType: 'uint256' },
      { name: '_challengePeriod', type: 'uint256', internalType: 'uint256' },
      {
        name: '_passkeyVerifier',
        type: 'address',
        internalType: 'address',
      },
      { name: '_zkJwtVerifier', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isRecoveryActive',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nonce',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'passkeyVerifier',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract IVerifier' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'startRecovery',
    inputs: [
      {
        name: 'intent',
        type: 'tuple',
        internalType: 'struct EIP712Lib.RecoveryIntent',
        components: [
          { name: 'wallet', type: 'address', internalType: 'address' },
          { name: 'newOwner', type: 'address', internalType: 'address' },
          { name: 'nonce', type: 'uint256', internalType: 'uint256' },
          { name: 'deadline', type: 'uint256', internalType: 'uint256' },
          { name: 'chainId', type: 'uint256', internalType: 'uint256' },
          {
            name: 'recoveryManager',
            type: 'address',
            internalType: 'address',
          },
        ],
      },
      { name: 'guardianIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'proof', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'submitProof',
    inputs: [
      { name: 'guardianIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'proof', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'threshold',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'updatePolicy',
    inputs: [
      {
        name: 'newGuardians',
        type: 'tuple[]',
        internalType: 'struct GuardianLib.Guardian[]',
        components: [
          {
            name: 'guardianType',
            type: 'uint8',
            internalType: 'enum GuardianLib.GuardianType',
          },
          { name: 'identifier', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
      { name: 'newThreshold', type: 'uint256', internalType: 'uint256' },
      {
        name: 'newChallengePeriod',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'wallet',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'zkJwtVerifier',
    inputs: [],
    outputs: [
      { name: '', type: 'address', internalType: 'contract IVerifier' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'PolicyUpdated',
    inputs: [
      { name: 'wallet', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProofSubmitted',
    inputs: [
      { name: 'intentHash', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'guardianIdentifier', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'approvalCount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RecoveryCancelled',
    inputs: [
      { name: 'intentHash', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'wallet', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RecoveryExecuted',
    inputs: [
      { name: 'intentHash', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'wallet', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: false, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RecoveryStarted',
    inputs: [
      { name: 'intentHash', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'wallet', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: false, internalType: 'address' },
      { name: 'deadline', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ThresholdMet',
    inputs: [
      { name: 'intentHash', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'thresholdMetAt', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'AlreadyInitialized', inputs: [] },
  { type: 'error', name: 'ChallengePeriodNotElapsed', inputs: [] },
  { type: 'error', name: 'GuardianAlreadyApproved', inputs: [] },
  { type: 'error', name: 'GuardianNotFound', inputs: [] },
  { type: 'error', name: 'IntentExpired', inputs: [] },
  { type: 'error', name: 'InvalidIntent', inputs: [] },
  { type: 'error', name: 'InvalidPolicy', inputs: [] },
  { type: 'error', name: 'InvalidProof', inputs: [] },
  { type: 'error', name: 'RecoveryAlreadyActive', inputs: [] },
  { type: 'error', name: 'RecoveryNotActive', inputs: [] },
  { type: 'error', name: 'ThresholdNotMet', inputs: [] },
  { type: 'error', name: 'Unauthorized', inputs: [] },
  { type: 'error', name: 'ZeroWallet', inputs: [] },
] as const;
